//https://www.geeksforgeeks.org/find-element-bitonic-array/

/* NEED TO SEARCH ELEMENT IN BITONIC ARRAY

SO FIRST FIND THE PEAK ELEMENT
IF KEY == BITONIC ELEMENT
	RETURN FOUND
IF KEY > BITONIC ELEMENT
	RETURN -1
	
OTHERWISE DIVIDE THE ARRAY INTO 2 HALVES
	ASCENDING HALF BEFORE THE BITONIC ELEMENT
	DESCENDING HALF AFTER THE BITONIC ELEMENT
	
	USE BINARY SEARCH IN THE HALVES
*/